### ISSUE TITLE
Fails if env variable is set to JSON (curly brackets, python dict)

### ISSUE THREAD

**Issue by Elijas** [MobileDynasty/pytest-env#11]
# Error
Fails with the following configuration
`pytest.ini`
```
[pytest]
env =
    JSON={"key": "value"}
```
due to 
`plugin.py`
```
        # Replace environment variables in value. for instance:
        # TEST_DIR={USER}/repo_test_dir.
        value = value.format(**os.environ)
```

# Simple suggestion:

use `R:` flag meaning `Raw value` (similar to python's `r"raw string"`) that will skip the `value.format` command. Yes, this way we won't be able to use other env variables in json/dict env variables, but in the current situation it's impossible to have json/dict env variables at all!

**Comment by EdgyEdgemond** [comment]
Is there a work around for this?
edit: 
The standard fix for maintaining {} in format strings through format works for this.
```
[pytest]
env = 
    JSON={{"key": "value"}}
```

**Comment by gaborbernat** [comment]
Development moved to https://github.com/pytest-dev/pytest-env

**Comment by Elijas** [comment]
> Development moved to https://github.com/pytest-dev/pytest-env

Thanks for letting us know! I've recreated the issue there.

**Comment by Elijas** [comment]
Fixed in  https://github.com/pytest-dev/pytest-env
