### ISSUE TITLE
Missing git version tags

### ISSUE THREAD

**Issue by kloczek** [MobileDynasty/pytest-env#17]
According to https://pypi.org/project/pytest-env/ latest version is 0.6.2 howevere there is no here any git tags marking versions.
Is it possible to add at lease last version tag?

**Comment by kloczek** [comment]
gentle ping 😃

**Comment by gaborbernat** [comment]
Development moved to https://github.com/pytest-dev/pytest-env

**Comment by kloczek** [comment]
closing.
Thx.
