### ISSUE TITLE
Possible to set an environment variable before running certain tests ?

### ISSUE THREAD

**Issue by stuaxo** [MobileDynasty/pytest-env#7]
Can I set an env var only for certain tests ?

Or set it - run some tests, and run the same ones with it unset ?

**Comment by stuaxo** [comment]
Not sure if it complicates things, but I'm testing django and the envvars enable or disable settings there.

**Comment by gaborbernat** [comment]
Development moved to https://github.com/pytest-dev/pytest-env

**Comment by stuaxo** [comment]
Thanks for the update.
I'm going to close this as I have recently moved projects so don't need the fraturem
